### PR TITLE
cleanup: Remove include & pkgconfig

### PR DESCRIPTION
**Pull request by Siosm**

### CODE REVIEW

**Comment by tsdgeos** [comment]
hmmmmm, right the docs can't be accessed locally because there's no local khelpcenter to view them.

@aleixpol do you think it'd make sense to add khelpcenter to the platform so people could see the docs locally and not depend whether they have internet or not when they need help?

**Comment by aleixpol** [comment]
I was about to say just "yes" but then I took a slightly deeper look. This would mean to bring khtml for all apps which isn't all that maintained and possibly has a few bugs.
The prospect of porting it to webkit/webengine doesn't look much better either.

If you think it makes a lot of sense, we could consider including khtml without headers. What do you think?

**Comment by tsdgeos** [comment]
> If you think it makes a lot of sense, we could consider including khtml without headers. What do you think?

I mean, we have khelpcenter because we think reading documentation without being connected to the internet is a valid usecase. So I think it makes lot of sense, yes :) If you accomplish that we momentarily have to include khtml without headers, i'm fine with that. I understand it wouldn't break other uses of khtml like okular, right?

About KHelpcenter and QtWebEngine, someone needs to put some pushing into https://phabricator.kde.org/D23866 or int the proposed alternative of QTextBrowser

**Comment by aleixpol** [comment]
If we were to go through QtWebEngine, apps that want khelpcenter would need to use the other runtime for other applications. Which I'm fine with, just needs agreeing on, and surely it would need the patch landing which seems unlikely after this time.

I'll add on my todo to add khelpcenter minus khtml on the platform for now.

**Comment by tsdgeos** [comment]
@Siosm assuming the local doc will magically work once khelpcenter lands on the platform (it should) can remove the like that erases share/doc?

**Comment by Siosm** [comment]
Updated. I will take a look at other KDE apps as I think some of them got their docs removed.

**Comment by tsdgeos** [comment]
I don't seem to have power to merge merge, so I'd say you go ahead and merge yourself :D

**Comment by aleixpol** [comment]
I don't have powers either. It would be useful to add some of us in case something happens to you. ;)

**Comment by Siosm** [comment]
@nedrichards @barthalion @bilelmoussaoui Can you add the KDE team members to maintainers here and also make sure they have access to kwrite too? Thanks

**Comment by bilelmoussaoui** [comment]
@Siosm done for this & kwrite as well

**Comment by Siosm** [comment]
Thanks!

**Pull request merged**
